version: "3.8"

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A code_review_agent.celery_app.celery worker --loglevel=info
    volumes:
      - .:/app
    environment:
      - HUGGINGFACE_TOKEN=${HUGGINGFACE_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"